# Generated by Django 3.0.5 on 2020-04-06 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20200406_1103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'default_permissions': ['view']},
        ),
    ]
