# Generated by Django 3.0.5 on 2020-04-06 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20200406_1109'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'default_permissions': 'view'},
        ),
    ]
