# Generated by Django 3.0.5 on 2020-04-06 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20200406_1118'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={},
        ),
    ]
